---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mavenproject
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: mavenproject
 template:
  metadata:
   name: mavenproject
   labels:
     app: mavenproject	 
  spec: 
    containers:
    - name: mavenprojectcontainer
      image: mohankumar1990/maven/maven-app:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebappsvc
spec:
  type: LoadBalancer
  selector:
   app: mavenproject
  ports:
   - port: 80
     targetPort: 8080
...
